
# Increases the amount of memory Gradle can use and optimizes the GC
# -XX:+UseZGC
    org.gradle.jvmargs=-Xmx4G
# Helps with build times
    org.gradle.parallel=true
# Caches Dependencies for faster build times.
    org.gradle.caching=false

# Fabric Properties
	# Get new versions at https://fabricmc.net/develop and https://lambdaurora.dev/tools/import_quilt.html
	minecraft_version=26.2
    loader_version=0.19.3

# Mod Properties
	mod_id = trimpatcher
	mod_version = 1.0
    # protocol version must be changed after each update with dual env changes
	maven_group = net.frozenblock
	archives_base_name = TrimPatcher

# Dependencies
	fabric_api_version=0.152.1+26.2
# Optimization
	sodium_version=mc26.2-0.9.0-fabric
    run_sodium = false
